include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.gr.dart"
    - "**/__generated/*.dart"
linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
    prefer_asserts_with_message: false
    prefer_if_elements_to_conditional_expressions: false
    sort_pub_dependencies: false
    no_default_cases: false
