name: codeblurb_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ">=3.1.1 <4.0.0"

dependency_overrides:
  analyzer: "6.0.0"
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.2
  easy_localization: ^3.0.2
  firebase_core: ^2.15.1
  flutter_form_builder: ^9.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  hooks_riverpod: ^2.4.0
  dio: ^5.3.2
  flutter_gen_runner: ^5.3.1
  jwt_decoder: ^2.0.1
  firebase_crashlytics: ^3.3.5
  firebase_remote_config: ^4.2.5
  flutter_animate: ^4.2.0+1
  pretty_dio_logger: ^1.3.1
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.13
  flutter_markdown: ^0.6.17+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6

  freezed: ^2.4.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
